// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFW2Zzfw3KySeBirFzth9IPlkeHHvD1K8',
    appId: '1:20839990605:web:9b3339ed5821b3a6182304',
    messagingSenderId: '20839990605',
    projectId: 'flutter-gemini-d0637',
    authDomain: 'flutter-gemini-d0637.firebaseapp.com',
    storageBucket: 'flutter-gemini-d0637.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtg2_rH8vlCUAs_4dgDpUtOcrF1bk-TXw',
    appId: '1:20839990605:android:8dfff413bfc8fe86182304',
    messagingSenderId: '20839990605',
    projectId: 'flutter-gemini-d0637',
    storageBucket: 'flutter-gemini-d0637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3WSJM2uvKV2sr0DkUEdWB6-mBwDKi98',
    appId: '1:20839990605:ios:7434c2f9d892fa62182304',
    messagingSenderId: '20839990605',
    projectId: 'flutter-gemini-d0637',
    storageBucket: 'flutter-gemini-d0637.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3WSJM2uvKV2sr0DkUEdWB6-mBwDKi98',
    appId: '1:20839990605:ios:7434c2f9d892fa62182304',
    messagingSenderId: '20839990605',
    projectId: 'flutter-gemini-d0637',
    storageBucket: 'flutter-gemini-d0637.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFW2Zzfw3KySeBirFzth9IPlkeHHvD1K8',
    appId: '1:20839990605:web:509499a41a2fd8ae182304',
    messagingSenderId: '20839990605',
    projectId: 'flutter-gemini-d0637',
    authDomain: 'flutter-gemini-d0637.firebaseapp.com',
    storageBucket: 'flutter-gemini-d0637.firebasestorage.app',
  );
}
